### ISSUE TITLE
藏書樓 is Everywhere

### ISSUE THREAD

**Issue by GLanguage** [wenyan-lang/wyg#1]
I noticed that `wyg i xxx` will create a `藏書樓` folder wherever I run the command. For example, if I run `wyg i 子曰` in `~`, it will be downloaded into `~/藏書樓/子曰`; but if I run the same command in `/`, it will be downloaded into `/藏書樓/子曰`; then I will have 2 same packages! Is that expected? Or is it a bug?

**Comment by antfu** [comment]
The current design is kinda like `npm` which installs packages locally instead of installing globally like `pip`. The behavior you described is expected.

**Comment by GLanguage** [comment]
Thanks a lot!
